---
- hosts: localhost
  gather_facts: False
  tasks:
  - name: Add a tower-bastion host
    add_host:
      name: tower{{ item }}.{{ TOWER_GUID }}.internal
      group: internal
    with_items:
      - 1
      - 2
      - 3


- hosts: internal
  gather_facts: False
  become: True
  become_method: sudo
  tasks:
  - name: Inject ssh.cfg
    template:
      src: ssh.cfg.j2
      dest: /tmp/ssh.cfg
